# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1c6af845beb0eae67cf241c1c8fe96d0609ed8c616995a63b2f9c8eedec41f10d2d023705a46aabdbc63a005b0e91ec7524b6d2fbd8be5c3586c548ce451cbfc

test:
  secret_key_base: 028167d80ca84640608b9e1cab7d95e9a9629bfb7f8eefe693119088e314b69fb5d9c1b9d128b1c0a059e96279da75708a601b0a017555723d867f5fcee42587

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
